### ISSUE TITLE
Failed to load the force-tab package

### ISSUE THREAD

**Issue by docprofsky** [lexicalunit/force-tab#1]
When opening Atom with `force-tab` installed, this error occurs.

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.5
**Thrown From**: [force-tab](https://github.com/lexicalunit/force-tab) package 0.2.0

### Stack Trace

Failed to load the force-tab package

```
At Duplicate key 'atom-text-editor:not([mini])'

Error: Duplicate key 'atom-text-editor:not([mini])'
  at Object.detectDuplicateKeys (/app.asar/node_modules/season/lib/cson.js:268:13)
  at /app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/app.asar/node_modules/season/lib/cson.js:170:14)
  at /app.asar/src/package.js:439:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/app.asar/src/package.js:436:46)
  at /app.asar/src/package.js:114:19
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at /app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
  at /app.asar/src/atom-environment.js:794:28

```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
activate-power-mode-delete 0.6.1 
atom-beautify 0.29.17 
atom-tag-wrapper 0.2.0 
atom-wrap-in-tag 0.6.0 
autocomplete-clang 0.10.0 
autocomplete-cmake 0.3.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.40 
automate-power-mode 0.2.1 
color-picker 2.2.5 
docblockr 0.9.1 
force-tab 0.2.0 
git-diff-details 1.4.0 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
js-refactor 0.7.5 
language-cmake 0.3.0 
language-ini 1.17.0 
language-swig-wrapper 0.2.0 
linter 1.11.21 
linter-jslint 11.1.0 
linter-markdown 3.1.0 
linter-write-good 0.8.0 
maybs-quit 1.3.0 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
nuclide-url-hyperclick 0.0.35 
pigments 0.39.0 
project-manager 3.3.3 
refactor 0.11.3 
script undefined 
scroll-sync 0.1.5 
split-diff 1.1.1 
swap-selection 0.4.0 
switch-header-source 0.22.0 
turbo-javascript 1.4.0 
```

**Comment by lexicalunit** [comment]
Sorry @docprofsky! Try v0.2.1, it should resolve the issue.

**Comment by docprofsky** [comment]
That fixes it.
